/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tutorial.HTTP;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//        HelloHTTP.postRequest();
//        HelloHTTP.getRequest();
        HelloHTTP.listAll();
        HelloHTTP.delete();
    }
}
