/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.JUnitTesting;

import main.java.JUnitTesting.ShoppingBasket;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void test() {
        ShoppingBasket basket = new ShoppingBasket();

    }
}
